name: markdown_widgets
description: "Widgets for survey questionnaires defined using markdown-like syntax."
version: 0.0.1
homepage: https://github.com/anusii/markdown_widgets

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.1.0
  characters: ^1.3.0
  circular_countdown_timer: ^0.2.4
  cupertino_icons: ^1.0.6
  dart_markdown: ^3.1.7
  flutter_form_builder: ^9.5.0
  flutter_html: ^3.0.0-beta.2
  flutter_markdown: ^0.7.4
  flutter_riverpod: ^2.5.3
  http: ^1.2.2
  intl: ^0.19.0
  markdown: ^7.2.2
  media_kit: ^1.1.11
  media_kit_libs_video: ^1.0.5
  media_kit_video: ^1.2.5
  number_paginator: ^0.4.1
  path_provider: ^2.1.5
  rdflib: ^0.2.11
  rename_app: ^1.6.1
  sensors_plus: ^6.0.1
  solidpod: ^0.6.1
  universal_io: ^2.2.2
  url_launcher: ^6.3.0
  window_manager: ^0.3.9

dev_dependencies:
  flutter_lints: ^3.0.0

#   dart_code_metrics:
#     git:
#       url: https://github.com/anusii/dart-code-metrics.git
#       ref: dev

# dependency_overrides:
#   # To have dart-code-metrics working
#   collection: ^1.19.0
  
flutter:
  uses-material-design: true

