name: markdown_widgets
description: "Widgets for survey questionnaires defined using markdown-like syntax."
version: 0.1.1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.1.0
  characters: ^1.3.0
  circular_countdown_timer: ^0.2.4
  cupertino_icons: ^1.0.6
  dart_markdown: ^3.1.7
  flutter_form_builder: ^9.5.0
  flutter_html: ^3.0.0-beta.2
  flutter_markdown: ^0.7.4
  flutter_riverpod: ^2.5.3
  http: any
  intl: ^0.19.0
  markdown: ^7.2.2
  number_paginator: ^0.4.1
  rdflib: any
  rename_app: ^1.6.1
  sensors_plus: ^6.0.1
  solidpod: ^0.6.1
  universal_io: ^2.2.2
  url_launcher: ^6.3.0
  video_player: ^2.9.2
  window_manager: ^0.3.9

dev_dependencies:
#  flutter_test:
#    sdk: flutter

  flutter_lints: ^3.0.0

  dart_code_metrics:
    git:
      url: https://github.com/anusii/dart-code-metrics.git
      ref: dev

dependency_overrides:
  # To have dart-code-metrics working
  collection: ^1.19.0
  
  # TODO 20240710 gjw dart-code-metrics DEPENDENCY ON pub_updater PROBLEM
  #
  # If Zheyuan can fix his dart-code-metrics fork this can probably be
  # removed.
#  file: ^7.0.0 # Use only if necessary
#  intl: ^0.19.0 # Use only if necessary

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

